### ISSUE TITLE
[Task] next.js 서버사이드 node.js 예시 만들기

### ISSUE THREAD

**Issue by verecahill** [codestates/BTAdAppProject-07#8]
### TODO
1. [ ] next.js 서버사이드 node.js 예시 만들기
2. [ ] aptos sdk 사용 (wallet 연동, nft 민팅, nft 판매, 전송)
3. [ ] sequalize 연동 예시
